
console.log("At start")


    setTimeout(()=>{
        try{
        console.log("Hey catch are u there to help me")
        a
        }
        catch(err){
            console.log("Some error is there")
        }
    }, 3000)

console.log("At end")